/* This file is auto-generated by SST. Do not edit. */
/* tslint:disable */
/* eslint-disable */
/* deno-fmt-ignore-file */

import "sst"
declare module "sst" {
  export interface Resource {
    "AdminPassword": {
      type: "sst.sst.Secret"
      value: string
    }
    "BeybstationApi": {
      name: string
      type: "sst.aws.Function"
      url: string
    }
    "BeybstationTable": {
      name: string
      type: "sst.aws.Dynamo"
    }
    "BeybstationWeb": {
      type: "sst.aws.StaticSite"
      url: string
    }
    "JwtSecret": {
      type: "sst.sst.Secret"
      value: string
    }
  }
}
